[package]
name = "manim-rs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A library for drawing and animating mathematical concepts. A Rust recreation of ManimCE."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
